name: tests

on:
  - push
  - pull_request

jobs:

  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "swiftlang/swift:nightly-5.3"
    name: Linux
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: APT experimental
      run: echo "deb http://deb.debian.org/debian experimental main" > /etc/apt/sources.list
    - name: APT Update
      run: apt-get update -y
    - name: Install libgit2
      run: apt-get -t experimental install -y libgit2-dev
    - name: Find headers
      run: dpkg -L libgit2-dev
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build --enable-test-discovery -v
    - name: Test
      run: swift test --enable-test-discovery -v

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install libgit2
      run: brew install libgit2
    - name: Swift Version
      run: swift --version
    - name: Release Build
      run: swift build -v -c release
    - name: Release Test
      run: swift test -v -c release
    - name: Debug Build
      run: swift build -v -c debug
    - name: Debug Test
      run: swift test -v -c debug
